//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetToGitHubWiki.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetToGitHubWiki.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file path of the assembly to document..
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string BaseLink {
            get {
                return ResourceManager.GetString("BaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot convert {0} to {1}..
        /// </summary>
        public static string CannotConvert {
            get {
                return ResourceManager.GetString("CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot be created: {0}.
        /// </summary>
        public static string CannotCreate {
            get {
                return ResourceManager.GetString("CannotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot be parsed..
        /// </summary>
        public static string CannotParse {
            get {
                return ResourceManager.GetString("CannotParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generates wiki pages for GitHub from source documentation..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while writing documentation for {0}.
        /// </summary>
        public static string ErrorWrittingDoc {
            get {
                return ResourceManager.GetString("ErrorWrittingDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ExternalLinks {
            get {
                return ResourceManager.GetString("ExternalLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file name of the Markdowns pages..
        /// </summary>
        public static string FileNameMode {
            get {
                return ResourceManager.GetString("FileNameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sets the full qualified name of the member as the Markdown file name..
        /// </summary>
        public static string FileNameModeFullName {
            get {
                return ResourceManager.GetString("FileNameModeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sets an MD5 hash (from the full name of the member) as the Markdown file name..
        /// </summary>
        public static string FileNameModeMd5 {
            get {
                return ResourceManager.GetString("FileNameModeMd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sets the type and member name without the namespace as the Markdown page name. May get collision if project has multiple types with the same name in different namespaces..
        /// </summary>
        public static string FileNameModeName {
            get {
                return ResourceManager.GetString("FileNameModeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For more information type {0} {1}.
        /// </summary>
        public static string GetHelp {
            get {
                return ResourceManager.GetString("GetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows the application help..
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The name of the default home page..
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The char which replaces all file name invalid chars..
        /// </summary>
        public static string InvalidCharReplacement {
            get {
                return ResourceManager.GetString("InvalidCharReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has an invalid format: {0}.
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string LinksFile {
            get {
                return ResourceManager.GetString("LinksFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The visibility of the nested types..
        /// </summary>
        public static string NestedTypeVisibility {
            get {
                return ResourceManager.GetString("NestedTypeVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nested type links are showed on their declaring type page..
        /// </summary>
        public static string NestedTypeVisibilityDeclaringType {
            get {
                return ResourceManager.GetString("NestedTypeVisibilityDeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nested type links are showed on both the namespace and their declaring type page..
        /// </summary>
        public static string NestedTypeVisibilityEverywhere {
            get {
                return ResourceManager.GetString("NestedTypeVisibilityEverywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nested type links are showed on the namespace page..
        /// </summary>
        public static string NestedTypeVisibilityNamespace {
            get {
                return ResourceManager.GetString("NestedTypeVisibilityNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot be found: {0}.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has not been specified..
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The folder path in which documentation files will be generated..
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Syntax.
        /// </summary>
        public static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Values.
        /// </summary>
        public static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The file path of the XML generated documentation..
        /// </summary>
        public static string Xml {
            get {
                return ResourceManager.GetString("Xml", resourceCulture);
            }
        }
    }
}
